// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_fifth_level_succeeded = "CggIv9GCrUcQAhAE"; // <GPGSID>
        public const string achievement_second_level_succeeded = "CggIv9GCrUcQAhAB"; // <GPGSID>
        public const string achievement_first_level_succeeded = "CggIv9GCrUcQAhAA"; // <GPGSID>
        public const string achievement_third_level_succeeded = "CggIv9GCrUcQAhAC"; // <GPGSID>
        public const string achievement_fourth_level_succeeded = "CggIv9GCrUcQAhAD"; // <GPGSID>
        public const string achievement_you_finished_the_game = "CggIv9GCrUcQAhAF"; // <GPGSID>

}

